#!/bin/sh
# Copyright (C) Research In Motion Limited 2010. All rights reserved.
#
# Warn when stubgen might be needed to be run
#

idl=`git diff-index --cached --name-only HEAD | grep bbnsl | grep idl`
bridge=`git diff-index --cached --name-only HEAD | grep bbnsl |grep OlympiaBridge`

if [ ! -z "${bridge}" ] && [ -z "${idl}" ] ; then
  echo "DANGER!  Changes to the bridge, but not to an idl file, do you need to run ob-stubgen?"
fi
