#!/bin/sh
#
# Warn about reviewed by nobody
#

cat $1 | grep 'Reviewed by NOBODY (OOPS!)' > /dev/null
if [ $? -eq 0 ] ; then
    echo "Reviewed by NOBODY!  Make sure to update the reviewed by line after a review."
fi
