#!/bin/sh
#
# Copyright (C) Research In Motion Limited 2010. All rights reserved.
#
# Warn if changes introduce a tab.
#

if git-rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

git diff --cached $against | grep $'\t'
if [ $? -eq 0 ] ; then
    echo "Error, there is a tab in your commit which will break the SCM build."
    exit 1
fi
