#!/bin/sh
#
# Warn if changes introduce trailing whitespace or an indent that uses a space before a tab. Exits with non-zero status if problems are found.
#

if git-rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

exec git diff-index --check --cached $against --
