#!/bin/sh
# Copyright (C) Research In Motion Limited 2010. All rights reserved.
#
# Check that a file has a proper RIM copyright header so we are consistent.
#

hasourcopyright="true"
for file in `git diff-index --cached --name-only HEAD | egrep '(.cpp|.h)'` ; do
# Only check cpp/h files for now
#for file in `git diff-index --name-only HEAD` ; do
    grep "Copyright" $file > /dev/null
        if [ ! $? -eq 0 ] ; then
        echo "No copyright found on $file"
        continue
    fi
    egrep 'Copyright \(C\) Research In Motion Limited 20(09-2010|10). All rights reserved.$' $file > /dev/null
    if [ ! $? -eq 0 ] ; then
        echo "The file \"$file\" does not contain a valid copyright header.  Please fix wording or update copyright years before committing.  Sample:"
        echo 'Copyright (C) Research In Motion Limited 2010. All rights reserved.'
        echo "Found:"
        grep "Copyright" $file
        echo
        hasourcopyright="false"
    fi
done
if [ ${hasourcopyright} = "false" ] ; then
    exit 1
fi
