#!/usr/bin/perl -w
# Copyright (C) Research in Motion Limited 2010. All rights reserved.
#
# Debug the device.

use strict;
use FindBin;
use lib $FindBin::Bin;
use olympiadirs;

sub pathToWBugDisp;

dieIfNotWindows();
dieIfBlackBerryIsNotConnected();
dieIfBlackBerryIsNotAccessible();
my $password = promptUser("Enter password: ", DoNotEchoInput) if blackBerryConnectionState()->{HasPassword};

my $wbugdispApp = pathToWBugDisp();
die "Could not find '$wbugdispApp'." if ! -e $wbugdispApp;

my $gdbApp = buildToolsDir() . "/bin/gdb70/arm-elf-gdb.exe";
die "Could not find '$gdbApp'." if ! -e $gdbApp;

my %buildSpec = buildSpecByHardwareId(devicePropertyValue("Hardware Id", $password));

# FIXME: We should determine the build config instead of hard coding "release".
my $elfFile = olympiaWebKitProductDir($buildSpec{PlatformName}, "release") . "/lib/OlympiaWebKit.elf";
if (! -e $elfFile) {
    print "*************************************************************\n";
    print "Could not find '$elfFile'.\n";
    print "\n";
    print "You must build Olympia for the $buildSpec{PlatformName} BlackBerry\n";
    print "Smartphone to be able to debug it.\n";
    print "*************************************************************\n";
    die;
}

print "Starting GDB using Olympia ELF file '$elfFile'.\n";
my @bugDispCmd = ($wbugdispApp, "-gdbport=2405");
push @bugDispCmd, "-w=$password" if $password;
system(@bugDispCmd);
system("$gdbApp --eval-command=\"target remote :2405\" $elfFile");
exit(0);

sub pathToWBugDisp
{
    my $wBugDispPath = $ENV{'OLYMPIAWBUGDISPDIR'} ? $ENV{'OLYMPIAWBUGDISPDIR'} : buildToolsDir() . "/bin";
    return "$wBugDispPath/wbugdisp.exe";
}
