#!/usr/bin/env perl
# Copyright (C) Research in Motion Limited 2010. All rights reserved.
#
# Run Fledge.

use strict;
use warnings;
use FindBin;
use lib $FindBin::Bin;
use olympiadirs;

# FIXME: We should add support for Mac Fledge.
dieIfNotWindows();

print "Starting Fledge simulator.\n";
runFledge(0);
exit(0);
