# Copyright (c) 2010 Research In Motion Limited. All rights reserved.
# Research In Motion Limited proprietary and confidential.

import unittest

from webkitpy.internal.mksintegrity import MKSIntegrity, MKSBug
from webkitpy.internal.rimbugzilla import RIMBugzilla, RIMBug

class MKSBugTest(unittest.TestCase):

    def test_handheld_discovered_on(self):
        bug = {"platform" : "Onyx"}
        self.assertEquals(MKSBug(RIMBug(bug)).handheld_discovered_on(), MKSBug._map_rim_to_mks_handhelds[bug["platform"]])
        bug = {"platform" : "Fledge"}
        self.assertEquals(MKSBug(RIMBug(bug)).handheld_discovered_on(), MKSBug._default_mks_handheld)

    def test_component_targeted_release(self):
        bug = {"os" : "6.0"}
        self.assertEquals(MKSBug(RIMBug(bug)).component_targeted_release(), MKSBug._map_rim_to_mks_release[bug["os"]])
        bug = {"os" : "Other"}
        self.assertEquals(MKSBug(RIMBug(bug)).component_targeted_release(), MKSBug._default_mks_releasee)

    def test_sub_component(self):
        bug = {"component" : "Core UI"}
        self.assertEquals(MKSBug(RIMBug(bug)).sub_component(), MKSBug._map_rim_to_mks_sub_component[bug["component"]])
        bug = {"component" : "New bugs"}
        self.assertEquals(MKSBug(RIMBug(bug)).sub_component(), MKSBug._default_mks_sub_component)
    
    def test_description(self):
        expected_mks_description = """This is an automatic bug report generated by the NeedsMKS Bot.

This is a sample bug.

Olympia Bug #12345 - %sshow_bug.cgi?id=12345.""" % RIMBugzilla.bug_server_url

        bug = {"id" : 12345, "long_description" : "This is a sample bug."}
        self.assertEquals(MKSBug(RIMBug(bug)).description(), expected_mks_description)

class MKSIntegrityTest(unittest.TestCase):

    _expected_mks_request = """<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://WebService.Indy.rim.net">
        <soapenv:Header/>
        <soapenv:Body>
            <web:createDevTask>
            <web:web_service_key>bugsdas890ad2320a22kzilla</web:web_service_key>
            <web:type_name>Handheld Dev Task</web:type_name>
            <web:change_number>Implementation</web:change_number>
            <web:field_values>Summary=<!-- MKS HTML -->Example Bug</web:field_values><web:field_values>Dev Task Component=Browser</web:field_values><web:field_values>Dev Task Sub Component=WebKit</web:field_values><web:field_values>Handheld Discovered On=ExampleDevice</web:field_values><web:field_values>Build Type=Development/Test</web:field_values><web:field_values>Development/Test Build=n/a</web:field_values><web:field_values>Customer Importance=2 - Medium</web:field_values><web:field_values>UI Impact=No</web:field_values><web:field_values>Description=<!-- MKS HTML -->This is an example bug.</web:field_values><web:field_values>Issue Type=</web:field_values><web:field_values>Reason=Triage</web:field_values><web:field_values>Issue Owner=a_person</web:field_values><web:field_values>Assigned User=+Assign Developer</web:field_values><web:field_values>Activity=Production</web:field_values><web:field_values>Finder Role=Developer</web:field_values><web:field_values>Internal Finder=a_person</web:field_values><web:field_values>Finder E-Mail=a_person@rim.com</web:field_values><web:field_values>Finder Company=**RIM</web:field_values><web:field_values>Reproducible=Yes</web:field_values><web:field_values>Frequency of Occurrence=Frequent</web:field_values><web:field_values>Component Target Releases=6.0.0</web:field_values><web:field_values>Technical Risk=3 - Average</web:field_values><web:field_values>Include in RN/KIL=Yes</web:field_values><web:field_values>What deliverable caused the problem?=</web:field_values><web:field_values>Why did this problem occur on the deliverable?=</web:field_values></web:createDevTask>
        </soapenv:Body>
    </soapenv:Envelope>"""

    def test_create_mks_request(self):
        mks_request = MKSIntegrity()._create_mks_request(bug_title="Example Bug",
                                                  bug_description="This is an example bug.",
                                                  component="Browser",
                                                  sub_component="WebKit",
                                                  build_type="Development/Test",
                                                  build_version="n/a",
                                                  component_targeted_release="6.0.0",
                                                  has_ui_impact="No",
                                                  reproducible="Yes",
                                                  frequency_of_occurrence="Frequent",
                                                  issue_type="",
                                                  handheld_discovered_on="ExampleDevice",
                                                  reporter="a_person",
                                                  reporter_email="a_person@rim.com",
                                                  issue_owner="a_person",
                                                  assignee="+Assign Developer")
        self.assertEquals(mks_request, self._expected_mks_request)

    _expected_mks_request_with_special_characters = """<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://WebService.Indy.rim.net">
        <soapenv:Header/>
        <soapenv:Body>
            <web:createDevTask>
            <web:web_service_key>bugsdas890ad2320a22kzilla</web:web_service_key>
            <web:type_name>Handheld Dev Task</web:type_name>
            <web:change_number>Implementation</web:change_number>
            <web:field_values>Summary=<!-- MKS HTML -->Example Bug with &lt;markup&gt;</web:field_values><web:field_values>Dev Task Component=Browser</web:field_values><web:field_values>Dev Task Sub Component=WebKit</web:field_values><web:field_values>Handheld Discovered On=ExampleDevice</web:field_values><web:field_values>Build Type=Development/Test</web:field_values><web:field_values>Development/Test Build=n/a</web:field_values><web:field_values>Customer Importance=2 - Medium</web:field_values><web:field_values>UI Impact=No</web:field_values><web:field_values>Description=<!-- MKS HTML -->This is an example bug that has {}, (), &lt;&gt;, ', &quot;, ; characters.</web:field_values><web:field_values>Issue Type=</web:field_values><web:field_values>Reason=Triage</web:field_values><web:field_values>Issue Owner=a_person</web:field_values><web:field_values>Assigned User=+Assign Developer</web:field_values><web:field_values>Activity=Production</web:field_values><web:field_values>Finder Role=Developer</web:field_values><web:field_values>Internal Finder=a_person</web:field_values><web:field_values>Finder E-Mail=a_person@rim.com</web:field_values><web:field_values>Finder Company=**RIM</web:field_values><web:field_values>Reproducible=Yes</web:field_values><web:field_values>Frequency of Occurrence=Frequent</web:field_values><web:field_values>Component Target Releases=6.0.0</web:field_values><web:field_values>Technical Risk=3 - Average</web:field_values><web:field_values>Include in RN/KIL=Yes</web:field_values><web:field_values>What deliverable caused the problem?=</web:field_values><web:field_values>Why did this problem occur on the deliverable?=</web:field_values></web:createDevTask>
        </soapenv:Body>
    </soapenv:Envelope>"""

    def test_create_mks_request_with_special_characters(self):
        mks_request = MKSIntegrity()._create_mks_request(bug_title="Example Bug with <markup>",
                                                  bug_description="This is an example bug that has {}, (), <>, ', \", ; characters.",
                                                  component="Browser",
                                                  sub_component="WebKit",
                                                  build_type="Development/Test",
                                                  build_version="n/a",
                                                  component_targeted_release="6.0.0",
                                                  has_ui_impact="No",
                                                  reproducible="Yes",
                                                  frequency_of_occurrence="Frequent",
                                                  issue_type="",
                                                  handheld_discovered_on="ExampleDevice",
                                                  reporter="a_person",
                                                  reporter_email="a_person@rim.com",
                                                  issue_owner="a_person",
                                                  assignee="+Assign Developer")
        self.assertEquals(mks_request, self._expected_mks_request_with_special_characters)

    _example_mks_response = """
    <?xml version="1.0" encoding="UTF-8"?>
    <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <soapenv:Body>
            <createDevTaskResponse xmlns="http://WebService.Indy.rim.net">
                <createDevTaskReturn>&lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
                &lt;Response&gt;
                &lt;Message&gt;Successfully created Handheld Dev Task. Job was successfully moved to Implementation State.&lt;/Message&gt;
                &lt;Value&gt;732916&lt;/Value&gt;
                &lt;/Response&gt;
                </createDevTaskReturn>
            </createDevTaskResponse>
        </soapenv:Body>
    </soapenv:Envelope>
    """

    _example_mks_response_with_decoded_html_entities = """
    <?xml version='1.0' encoding='utf-8'?>
    <soapenv:envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <soapenv:body>
            <createdevtaskresponse xmlns="http://WebService.Indy.rim.net">
                <createdevtaskreturn><?xml version="1.0" encoding="ISO-8859-1"?>
                <Response>
                <Message>Successfully created Handheld Dev Task. Job was successfully moved to Implementation State.</Message>
                <Value>732916</Value>
                </Response>
                </createdevtaskreturn>
            </createdevtaskresponse>
        </soapenv:body>
    </soapenv:envelope>
    """

    def test_parse_mks_response_for_mks_id(self):
        self.assertEquals(MKSIntegrity()._parse_mks_response_for_mks_id(self._example_mks_response), 732916)
        self.assertEquals(MKSIntegrity()._parse_mks_response_for_mks_id(self._example_mks_response_with_decoded_html_entities), 732916)
